### ISSUE TITLE
setCenter?

### ISSUE THREAD

**Issue by hotfusion** [radarlabs/radar-sdk-js#191]
Hi Radar.io Team,

I’m having trouble figuring out how to change the center (same as Google maps provides setCenter method and  mapbox as well) using the SDK. I couldn’t find any details about it in the documentation or examples. Am I missing something, or does the SDK not support this functionality?

By the way, your API documentation is fantastic!

Thanks,

**Comment by kochis** [comment]
The map object is an instance of a [MapLibre Map](https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/) object, so any of the functions on this page can be used on the map.

Some of the functions for moving the position of the map

[map.easeTo()](https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#easeto)
[map.flyTo()](https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#flyto)
[map.jumpTo()](https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#jumpto)

```js
const map = Radar.ui.map({
  container: 'map',
  style: 'radar-default-v1',
  center: [-73.990550, 40.735225],
});

// update map with new center
map.flyTo({
  center: [newLng, newLat],
});
```
