### ISSUE TITLE
Include mobile browser compatibility into project's README

### ISSUE THREAD

**Issue by andregoiano** [radarlabs/radar-sdk-js#2]
Hey guys, is it possible to include information about current mobile browser compatibility for this SDK as part of the project's information. That will help push adoption, if people can grasp most platforms allow it already.

**Comment by nickpatrick** [comment]
Thanks! We'll queue this up for a future README update

**Comment by andregoiano** [comment]
Fantastic. This SDK has lots of potential, good luck with the beta roll-out.
