### ISSUE TITLE
There doesn't seem to be any guide on Geofencing from the SDK

### ISSUE THREAD

**Issue by Zonalds** [radarlabs/radar-sdk-js#41]
I recently implemented all needed methods. Everything checks out excepth there is no information on Geofencing from the SDK.

Is this supported?

**Comment by nickpatrick** [comment]
@Zonalds are you looking for a web SDK equivalent to `Radar.startTracking()` in the iOS (https://radar.io/documentation/sdk/ios#background-tracking-for-geofencing) and Android (https://radar.io/documentation/sdk/android#background-tracking-for-trips) SDKs? Background tracking isn't possible on web, but continuous tracking in the foreground is possible.

**Comment by Zonalds** [comment]
I failed to mention I was looking for geofencing from the web (web JS SDK). I took a look at the source code and it doesn't seem to have that API. 

I will try to add it and create a PR when I am ready to use it.

**Comment by nickpatrick** [comment]
That's right, there's no `Radar.startTracking()` in the web SDK. Historically this was because web browsers don't support background location tracking, but we've thought about adding it to support continuous location tracking in the foreground. Can you share a little bit more about your use case?

**Comment by Zonalds** [comment]
What I mean is the `create` a geofence API, sort of pinpoint a location. A merchant enters coordinates and create geofence for a store. The tracking will be done only on mobile.
In details I need the the service providers providers to geofence their store location on web (this is the only way I want them to do so). And their customers will only use mobile tracking features to locate this store.
