### ISSUE TITLE
ts types + es build

### ISSUE THREAD

**Issue by moczix** [radarlabs/radar-sdk-js#62]
hello, could you write typings for library? and build es treeshakeable dist? i want to use it in angular and now i must write my own types

**Comment by jackLIT** [comment]
Would like to second this comment. Would love to use this library but need the typings!

**Comment by kochis** [comment]
Just wanted to post an update, we now have a v4 version of the SDK in beta, that has been fully updated with typescript.

You can check it out here: https://github.com/radarlabs/radar-sdk-js/tree/v4-beta (see [MIGRATION](https://github.com/radarlabs/radar-sdk-js/blob/v4-beta/MIGRATION.md) for more details on upgrading to the latest version)

**Comment by kochis** [comment]
Types are now available: https://github.com/radarlabs/radar-sdk-js/blob/master/src/types.ts
