### ISSUE TITLE
Is there radar for nodejs??

### ISSUE THREAD

**Issue by tngflx** [radarlabs/radar-sdk-js#93]
Its only meant for the web? what about backend with nodejs?

**Comment by tngflx** [comment]
I've tried npm install, come with rollup dependency error. Is this project even maintained??

**Comment by corypisano** [comment]
hi @tngflx yes this is the Web JS SDK, and makes use of the Browser Geolocation APIs which would not apply for node. We don't have a dedicated node.js SDK at this time, but you can call the APIs directly

Documentation: 
- https://radar.com/documentation/sdk/web
- https://radar.com/documentation/api

**Comment by tngflx** [comment]
Thank you for reply. I've noticed u guys also use google map as map layout. Does it mean you guys actually used google map as backend?
